#Weather Forcast thingy
# Authors: Jude, Justas and Dave
print("=========================================")
print("    Defo not weather forcast thingy")
print("=========================================")

print("Which day do you want the weather for (from today 14/11/2025)?")
print("1. Today")
print("2. Saturday")
print("3. Sunday")
print("4. Monday")
print("5. Tuesday")
print("6. Wednesday")
print("7. Thursday")
print("8. txt file of the forcast")
day = int(input("Enter the number corresponding to the day (1 - 8): "))

while True:
    if day == 1:
        print("Temperature: 9°C")
        print("Feels like: 0°C")
        print("UV Index: 0 (Low)")
        print("Wind: 24mph ENE")
        print("Precipitation: 39mm")
        print("Visibility: 3 miles")
        print("Humidity: 91%")
        print("Preassure: 1,003 mbar")
    if day == 2:
        print("Tempurature: 9 - 11°C")
        print("Feels like: 2 - 7°C")
        print("UV Index: 1 (Low)")
        print("Wind: 9 - 19mph")
        print("Precipitation: 7mm")
        print("Visibility: 5 - 13 miles")
        print("Humidity: 92%")
        print("Preassure: 1,010 mbar")
    if day == 3:
        print("Tempurature: 4 - 9°C")
        print("Feels like: 0 - 5°C")
        print("UV Index: 1 (Low)")
        print("Wind: 6 - 11mph")
        print("Precipitation: 0mm")
        print("Visibility: 10 - 23 miles")
        print("Humidity: 79%")
        print("Preassure: 1,015 mbar")
    if day == 4:
        print("Tempurature: 1 - 6°C")
        print("Feels like: -4 - 4°C")
        print("UV Index: 1 (Low)")
        print("Wind: 5 - 11mph")
        print("Precipitation: 0mm")
        print("Visibility: 18 - 23 miles")
        print("Humidity: 79%")
        print("Preassure: 1,024 mbar")
    if day == 5:
        print("Tempurature: 0 - 6°C")
        print("Feels like: -2 - 1°C")
        print("UV Index: 1 (Low)")
        print("Wind: 5 - 12mph")
        print("Precipitation: 0mm")
        print("Visibility: 11 - 19 miles")
        print("Humidity: 84%")
        print("Preassure: 1,017 mbar")
    if day == 6:
        print("Tempurature: -1 - 4°C")
        print("Feels like: -7 - -2°C")
        print("UV Index: 1 (Low)")
        print("Wind: 10 17mph")
        print("Precipitation: 1mm")
        print("Visibility: 6 - 21 miles")
        print("Humidity: 81%")
        print("Preassure: 1,014 mbar")
    if day == 7:
        print("Tempurature: -2 - 3°C")
        print("Feels like: -7 - -1°C")
        print("UV Index: 1 (Low)")
        print("Wind: 6 - 11mph")
        print("Precipitation: 0mm")
        print("Visibility: 19 - 22 miles")
        print("Humidity: 78%")
        print("Preassure: 1,015 mbar")
    if day == 8:
        with open("Weather Forecast Thingy.txt", "w") as f:
            f.write("Weather Forecast Thingy\n")
            f.write("\n\n")
            f.write("Day 1 (Today):\n")
            f.write("Temperature: 9°C\nFeels like: 0°C\nUV Index: 0 (Low)\nWind: 24mph ENE\nPrecipitation: 39mm\nVisibility: 3 miles\nHumidity: 91%\nPreassure: 1,003 mbar\n\n")
            f.write("Day 2 (Saturday):\n")
            f.write("Tempurature: 9 - 11°C\nFeels like: 2 - 7°C\nUV Index: 1 (Low)\nWind: 9 - 19mph\nPrecipitation: 7mm\nVisibility: 5 - 13 miles\nHumidity: 92%\nPreassure: 1,010 mbar\n\n")
            f.write("Day 3 (Sunday):\n")
            f.write("Tempurature: 4 - 9°C\nFeels like: 0 - 5°C\nUV Index: 1 (Low)\nWind: 6 - 11mph\nPrecipitation: 0mm\nVisibility: 10 - 23 miles\nHumidity: 79%\nPreassure: 1,015 mbar\n\n")
            f.write("Day 4 (Monday):\n")
            f.write("Tempurature: 1 - 6°C\nFeels like: -4 - 4°C\nUV Index: 1 (Low)\nWind: 5 - 11mph\nPrecipitation: 0mm\nVisibility: 18 - 23 miles\nHumidity: 79%\nPreassure: 1,024 mbar\n\n")
            f.write("Day 5 (Tuesday):\n")
            f.write("Tempurature: 0 - 6°C\nFeels like: -2 - 1°C\nUV Index: 1 (Low)\nWind: 5 - 12mph\nPrecipitation: 0mm\nVisibility: 11 - 19 miles\nHumidity: 84%\nPreassure: 1,017 mbar\n\n")
            f.write("Day 6 (Wednesday):\n")
            f.write("Tempurature: -1 - 4°C\nFeels like: -7 - -2°C\nUV Index: 1 (Low)\nWind: 10 17mph\nPrecipitation: 1mm\nVisibility: 6 - 21 miles\nHumidity: 81%\nPreassure: 1,014 mbar\n\n")
            f.write("Day 7 (Thursday):\n")   
            f.write("Tempurature: -2 - 3°C\nFeels like: -7 - -1°C\nUV Index: 1 (Low)\nWind: 6 - 11mph\nPrecipitation: 0mm\nVisibility: 19 - 22 miles\nHumidity: 78%\nPreassure: 1,015 mbar\n")

    else:
        print("Invalid input. Please enter a number between 1 and 8.")
        day = int(input("Enter the number corresponding to the day (1 - 8): "))
        continue
    